name: Clang Format Check

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install clang-format
      run: sudo apt-get install -y clang-format

    # - name: Run clang-format check
    #   run: |
    #     find . -regex '.*\.\(cpp\|hpp\|cc\|cxx\|c\|h\)' -exec clang-format --dry-run --Werror {} +

    - name: Apply clang-format (only on push)
      if: github.event_name == 'push'
      run: |
        find . -regex '.*\.\(cpp\|hpp\|cc\|cxx\|c\|h\)' -exec clang-format -i {} +
