name: Clang Format Check

on:
  pull_request:
    branches:
      - net
      - ecs
      - graphic
  push:
    branches:
      - net
      - ecs
      - graphic

jobs:
  clang-format:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install clang-format
      run: sudo apt-get install -y clang-format

    - name: Apply clang-format (only on push)
      if: github.event_name == 'push'
      run: |
        find . -regex '.*\.\(cpp\|hpp\|cc\|cxx\|c\|h\)' -exec clang-format -i {} +

    - name: Configure git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Check for changes
      id: changes
      run: |
        git diff --exit-code || echo "has_changes=true" >> $GITHUB_ENV
        echo "has_changes=false" >> $GITHUB_ENV || true

    - name: Commit and push changes
      if: github.event_name == 'push' && env.has_changes == 'true'
      run: |
        git add .
        git commit -m "FORMAT : Apply clang-format changes"
        git push
